services:
  - type: web
    name: valorant-api
    runtime: python
    region: oregon
    plan: free
    branch: main

    # Comandos
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # Variáveis de ambiente
    envVars:
      - fromGroup: valorant-api-universitario

      - key: ENVIRONMENT
        value: production

    # Versão do Python
    pythonVersion: "3.11.9"

    healthCheckPath: /health

    numInstances: 1
    autoDeploy: true